CREATE DATABASE IF NOT EXISTS itbkanban;
USE itbkanban;
CREATE TABLE `itbkanban`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taskTitle` TEXT(100) NOT NULL,
  `taskDescription` TEXT(500) NULL,
  `taskAssignees` TEXT(30) NULL,
  `taskStatus` ENUM('NO_STATUS', 'TO_DO', 'DOING', 'DONE') NOT NULL,
  `createdOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

SET time_zone = '+00:00';